### PR TITLE
Reworked README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Sorted files

- General formatting / spacing

- Added license badge

- Added alternate preview 

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/SoCDP8

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@fpw Please review this PR~

**Comment by fpw** [comment]
Hi!

Sorry for the long delay, I somehow didn't see this PR.

Thanks for trying to improve the project! A few remarks:

- please don't rename the folders, the names (src, docs, etc.) are kind of standard for projects like this and there are scripts in the system that depends on them
- the project actually has two licenses: OpenHardware for the hardware and AGPL3 for the software. Is it possible to add another badge?
- I don't like \<br\> in Markdown as it's non-standard. Maybe paragraphs can be used instead.
- Some important information was removed, for example that the machine is from 1968
- using a monospace font for terms like Raspberry Pi looks odd, maybe it could use a normal emphasis like italics?

**Comment by ElectronicsArchiver** [comment]
> Sorry for the long delay, I somehow didn't see this PR.

That happens to me quite a lot..

> please don't rename the folders, the names (src, docs, etc.) are kind of standard for projects like this and there are scripts in the system that depends on them

I can revert that, sure.

> the project actually has two licenses: OpenHardware for the hardware and AGPL3 for the software. Is it possible to add another badge?

Sure.

> I don't like <br> in Markdown as it's non-standard. Maybe paragraphs can be used instead.

I'm afraid it's perfectly normal, in fact its the other way around,
Markdown is an extension of HTML, only that GitHubs flavor doesn't
allow most css attributes.

Use break takes to add vertical spacing for sectiting and general
clarity, the only alternative would be \\ which is as awful as
doing it for macros in C / C++


> Some important information was removed, for example that the machine is from 1968

Sorry about that, will fix it.

> using a monospace font for terms like Raspberry Pi looks odd, maybe it could use a normal emphasis like italics?

Sure, if you want that I can change it~

**Comment by ElectronicsArchiver** [comment]
@fpw Btw, I would recommend creating a GitHub Profile page if have any relevant / public socials or want to show off something other than just pinning projects.

Let me know if you want to know more about that~

**Comment by ElectronicsArchiver** [comment]
@fpw GitHub - by now - actually recognizes multiple licenses, 
however Open Hardware **1.2** is not regocnized, only 2.0 versions.

In general these are recognized:
https://choosealicense.com/appendix/

The 2.0 revisions are much clearer and have 3 different
flavors depending on what you want to allow.

**Comment by ElectronicsArchiver** [comment]
@fpw Done with the requested changes.

**Comment by fpw** [comment]
Thanks again!

**Pull request merged**
